version: '3.1'
services:
  app:
    image: docker.io/makos/odoo-s3-backup
    build:
      context: .
    environment:
      - PGHOST=
      - PGPORT=5432
      - PGUSER=
      - PGPASSWORD=
      - PGDATABASE=
      - ODOO_DATA_DIR=/var/lib/odoo
      - S3_ENDPOINT=
      - S3_ACCESS_KEY=
      - S3_SECRET_KEY=
      - S3_BUCKET=
